contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #chloroplast channel"
    url: https://nfcore.slack.com/channels/chloroplast
    about: Discussion about the nf-core/chloroplast pipeline
